### ISSUE TITLE
Chatbar bug - A second spawns under with a max length string - Characters do not wrap.

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [hugeblank/KristChat#8]
**Describe the bug**

**To Reproduce**
1. Go to any chatroom
2. Put a max length string (no spaces) in the chatbar.
2.5 See error - Instead of wrapping, the characters continue offscreen.
3. Begin erasing the characters.
4. See error - A second chatbar will appear under the first.

**Expected behavior**
I would expect it to wrap to a second line, and also to just remove the characters from the bar, and only have one bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/34724753/103486688-8f22f780-4dcd-11eb-98fe-3d19a4c0cef0.png)

**Platform (please complete the following information):**
 - Platform: CraftOS-PC
 - Version 2.5.1
 - ComputerCraft Version: [e.g. 1.95.0]

**Additional context**

**Comment by hugeblank** [comment]
C-C-C-C-COMBO BUG!!!

This is two things going wrong:
1. Strings without spaces that span the entire line and then some don't get split
2. The window, when reducing in size writes over the post board.

Thanks for reporting this I'll have it fixed ASAP
